// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "8y:o?fww_mjqF@9FgSmE":
            case "girl Head":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d e d e . . . . 
. . . . 4 5 5 d d d d d . . . . 
. . . . 5 5 . . d d d . . . . . 
. . . 4 5 . e f d d d . . . . . 
. . . 4 4 . e e 3 3 3 3 . . . . 
. . . . . 3 3 3 e 3 3 3 3 3 . . 
. . . . . 3 3 d 3 e e e 3 3 . . 
. . . . . . 3 3 3 3 3 3 e d . . 
. . . . . . 3 3 3 3 3 3 3 e . . 
. . . . . . 3 3 3 3 3 3 3 . e . 
`;
            case "g[@jf8cm4Jxnm}_T=CC[":
            case "girlBottom":return img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`;
            case "-f[)o:Q_G$SIpaJ_tAx_":
            case "boy":return img`
........ff......
......ffffff....
......ffffff....
.....fffffff....
.....fffddfff...
.....ffdededff..
.....ffdfdfdff..
....fffdfdfdff..
....fffddddfffc.
....ffffddfffcf.
...ffffbbbbbcff.
..fffffbbbbcbff.
..ffffbbe1cbbff.
..fffffeee1bfff.
...fffffeeeffff.
...ffffe55effff.
....fff5555ffff.
....fff5555ffff.
....fff5555fff..
.....ff5555fff..
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "boy animation1":
            case "z":return [img`
........ff................
......ffffff..............
......ffffff..............
.....fffffff..............
.....fffddfff.............
.....ffdededff............
.....ffdfdfdff............
....fffdfdfdff............
....fffddddfffc...........
....ffffddfffcf...........
...ffffbbbbbcff...........
..fffffbbbbcbff...........
..ffffbbe1cbbff...........
..fffffeee1bfff...........
...fffffeeeffff...........
...ffffe55effff...........
....fff5555ffff...........
....fff5555ffff...........
....fff5555fff............
.....ff5555fff............
.......55f5...............
.......5..5...............
.......5..f...............
.......5..................
.......5..................
.......f..................
`, img`
..........................
..........................
..........................
......fffff...............
.....fffddff..............
.....ffdededf.............
....fffdfdfdf.............
...ffffdfdfdf.............
..fffffddddff.c...........
..ffffffddfffc............
.ffffffbbbbbcf............
.ffffffbbbbcbf............
.fffffbbe1cbbf............
.ffffffeee1bff............
.fffffffeeefff............
.ffffffe55efff............
.ffffff5555ff.............
...ffff5555ff.............
....fff5555ff.............
...ffff5555ff.............
..fffff55f5f..............
..fffff5ff5...............
...ffff5f.f...............
.....ff5f.................
......f5f.................
.......f..................
`, img`
..................ff......
................ffffff....
................ffffff....
...............fffffff....
...............fffddfff...
...............ffdededff..
...............ffdfdfdff..
..............fffdfdfdff..
..............fffddddffff.
..............ffffddfffff.
.............ffbbbbbbbbff.
............fffbbbbbbbbff.
............fffbbbebbbbff.
............fffbdeeedbbff.
.............ffffbcbbffff.
.............ffff5c55ffff.
..............fff5c55ffff.
..............fff5c55ffff.
..............fff5555fff..
...............ff5555fff..
.................55f5.....
.................5..5.....
.................5..f.....
.................5........
.................5........
.................f........
`, img`
..........................
............ffffffff......
.........fffffffffff......
........fffffffffffff.....
.......fffffffffffddff....
......fffffffffffdeded....
.....ffffffffffffdfdfd....
.....ffffffffffffdfdfd....
....fffffffffcfffdddd.....
....ffffffffffcfffdd......
...ffffffffffffcfbbbb.....
...fffffffffffffcbbbbe....
..ffffffffffffffbcedeb....
..ffffffffffffffbeeebb....
.fffffffffffffffbdebbb....
.ffffffffffffffff55e5.....
.ffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff55f5.....
fffffffffffffffff5ff5.....
.ffffffffffffffff5f.f.....
.fffffffffffffff.5........
.....ffffffff....5........
......fffff......f........
`, img`
..........................
............fffff.........
...........ffffffff.......
.........ffffffffff.......
........fffffddfffff......
.......fffffdededffff.....
.......fffffdfdfdffff.....
.......fffffdfdfdfffff....
.......fcfffddddffffff....
......fffcfffddfffffff....
......ffffcfbbbbffffff....
......fffffcbbbbefffff....
......fffffbcedebfffff....
......fffffbeeebbfffff....
......fffffbdebbbfffff....
......ffffff55e5fffff.....
......ffffff5555fffff.....
.......fffff5555fffff.....
.......fffff5555ffff......
.......fffff5555ff........
.......fffff55f5f.........
........ffff5f.5..........
.........fff5f.f..........
..........ff5.............
...........f5.............
...........ff.............
`];
            case "boy animation2":
            case "%}XLY1rY?":return [img`
........ff................
......ffffff..............
......ffffff..............
.....fffffff..............
.....fffddfff.............
.....ffdededff............
.....ffdfdfdff............
....fffdfdfdff............
....fffddddfffc...........
....ffffddfffcf...........
...ffffbbbbbcff...........
..fffffbbbbcbff...........
..ffffbbe1cbbff...........
..fffffeee1bfff...........
...fffffeeeffff...........
...ffffe55effff...........
....fff5555ffff...........
....fff5555ffff...........
....fff5555fff............
.....ff5555fff............
.......55f5...............
.......5..5...............
.......5..f...............
.......5..................
.......5..................
.......f..................
`, img`
..........................
..........................
..........................
......fffff...............
.....fffddff..............
.....ffdededf.............
....fffdfdfdf.............
...ffffdfdfdf.............
..fffffddddff.c...........
..ffffffddfffc............
.ffffffbbbbbcf............
.ffffffbbbbcbf............
.fffffbbe1cbbf............
.ffffffeee1bff............
.fffffffeeefff............
.ffffffe55efff............
.ffffff5555ff.............
...ffff5555ff.............
....fff5555ff.............
...ffff5555ff.............
..fffff55f5f..............
..fffff5ff5...............
...ffff5f.f...............
.....ff5f.................
......f5f.................
.......f..................
`, img`
..................ff......
................ffffff....
................ffffff....
...............fffffff....
...............fffddfff...
...............ffdededff..
...............ffdfdfdff..
..............fffdfdfdff..
..............fffddddffff.
..............ffffddfffff.
.............ffbbbbbbbbff.
............fffbbbbbbbbff.
............fffbbbebbbbff.
............fffbdeeedbbff.
.............ffffbcbbffff.
.............ffff5c55ffff.
..............fff5c55ffff.
..............fff5c55ffff.
..............fff5555fff..
...............ff5555fff..
.................55f5.....
.................5..5.....
.................5..f.....
.................5........
.................5........
.................f........
`, img`
..........................
............ffffffff......
.........fffffffffff......
........fffffffffffff.....
.......fffffffffffddff....
......fffffffffffdeded....
.....ffffffffffffdfdfd....
.....ffffffffffffdfdfd....
....fffffffffcfffdddd.....
....ffffffffffcfffdd......
...ffffffffffffcfbbbb.....
...fffffffffffffcbbbbe....
..ffffffffffffffbcedeb....
..ffffffffffffffbeeebb....
.fffffffffffffffbdebbb....
.ffffffffffffffff55e5.....
.ffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff5555.....
fffffffffffffffff55f5.....
fffffffffffffffff5ff5.....
.ffffffffffffffff5f.f.....
.fffffffffffffff.5........
.....ffffffff....5........
......fffff......f........
`, img`
..........................
............fffff.........
...........ffffffff.......
.........ffffffffff.......
........fffffddfffff......
.......fffffdededffff.....
.......fffffdfdfdffff.....
.......fffffdfdfdfffff....
.......fcfffddddffffff....
......fffcfffddfffffff....
......ffffcfbbbbffffff....
......fffffcbbbbefffff....
......fffffbcedebfffff....
......fffffbeeebbfffff....
......fffffbdebbbfffff....
......ffffff55e5fffff.....
......ffffff5555fffff.....
.......fffff5555fffff.....
.......fffff5555ffff......
.......fffff5555ff........
.......fffff55f5f.........
........ffff5f.5..........
.........fff5f.f..........
..........ff5.............
...........f5.............
...........ff.............
`, img`
........ff................
......ffffff..............
......ffffff..............
.....fffffff..............
.....fffddfff.............
.....ffdededff............
.....ffdfdfdff............
....fffdfdfdff............
....fffddddfffc...........
....ffffddfffcf...........
...ffffbbbbbcff...........
..fffffbbbbcbff...........
..ffffbbe1cbbff...........
..fffffeee1bfff...........
...fffffeeeffff...........
...ffffe55effff...........
....fff5555ffff...........
....fff5555ffff...........
....fff5555fff............
.....ff5555fff............
.......55f5...............
.......5..5...............
.......5..f...............
.......5..................
.......5..................
.......f..................
`];
            case "girl animationhead":
            case "wrO3jZ)BxZS6|#TFCR7c":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d e d e . . . . 
. . . . 4 5 5 d d d d d . . . . 
. . . . 5 5 . . d d d . . . . . 
. . . 4 5 . e f d d d . . . . . 
. . . 4 4 . e e 3 3 3 3 . . . . 
. . . . . 3 3 3 e 3 3 3 3 3 . . 
. . . . . 3 3 d 3 e e e 3 3 . . 
. . . . . . 3 3 3 3 3 3 e d . . 
. . . . . . 3 3 3 3 3 3 3 e . . 
. . . . . . 3 3 3 3 3 3 3 . e . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . 4 5 5 d e d e d . . . . 
. . . . 5 5 . . d d d d . . . . 
. . . 4 5 . e f d d . . . . . . 
. . . 4 4 . e e 3 3 3 3 . . . . 
. . . . . 3 3 e 3 3 3 3 3 3 . . 
. . . . . 3 3 d e 3 3 3 3 3 . . 
. . . . . 3 3 3 e d 3 3 3 3 . . 
. . . . . 3 3 3 3 e 3 3 3 3 . . 
. . . . . . 3 3 3 e 3 3 3 . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . 4 5 5 d e d e d . . . . 
. . . . 5 5 . . d d d d . . . . 
. . . 4 5 . . . e e f . . . . . 
. . . 4 4 . . 3 e f f 3 . . . . 
. . . . . 3 3 3 e e e 3 3 3 . . 
. . . . . 3 3 3 d e 3 3 3 3 . . 
. . . . . 3 3 3 3 e 3 3 3 3 . . 
. . . . . 3 3 3 3 e d 3 3 3 . . 
. . . . . . 3 3 3 e 3 3 3 . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . 4 5 5 d e d e d . . . . 
. . . . 5 5 . . d d d d e f . . 
. . . 4 5 . . . d d . . e e . . 
. . . 4 4 . . 3 3 3 3 e e . . . 
. . . . . 3 3 3 3 3 e e 3 3 . . 
. . . . . 3 3 3 3 e e d 3 3 . . 
. . . . . 3 3 3 d e 3 3 3 3 . . 
. . . . . 3 3 3 e e 3 3 3 3 . . 
. . . . . . 3 3 e 3 3 3 3 . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 4 . . . . . 
. . . . . . . 5 5 5 5 5 . . . . 
. . . . . . 5 5 4 5 d d . . . . 
. . . . . . 5 5 d d d d . . . . 
. . . . . . 5 5 d e d e . . . . 
. . . . 4 5 5 d d d d d . . . . 
. . . . 5 5 . . d d d . . . . . 
. . . 4 5 . e f d d d . . . . . 
. . . 4 4 . e e 3 3 3 3 . . . . 
. . . . . 3 3 3 e 3 3 3 3 3 . . 
. . . . . 3 3 d 3 e e e 3 3 . . 
. . . . . . 3 3 3 3 3 3 e d . . 
. . . . . . 3 3 3 3 3 3 3 e . . 
. . . . . . 3 3 3 3 3 3 3 . e . 
`];
            case "girl animationfeet":
            case "anim1":return [img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`, img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`, img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`, img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`, img`
. . . . . . 6 6 6 6 6 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . 6 6 . . . 6 6 . . . 
. . . . . . d d . . . d d . . . 
. . . . . 9 9 9 . . . 9 9 9 . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
