let mySprite2: Sprite = null
let mySprite: Sprite = null
let girl = false
scene.setBackgroundColor(7)
game.splash("girls and boys actions and thoughts are different")
game.showLongText("example: girls can use magic, boys can't but are better with a physical attack. girls's regular attack does little damage but before you can cast spells you have to learn them. learn spells by leveling up then press B, when pressing B, you will get 2 options, menu and magic, magic list the magic you know so you can use them. menu opensthe menu where you can use items, change equipment, and learn about the magic you know, and show this guide. use A to use a normal attack.and that is all this guide possesses.", DialogLayout.Full)
if (game.ask("girl", "boy")) {
    girl = true
    mySprite = sprites.create(img`
        ................
        ................
        ..........4.....
        .......55555....
        ......5545dd....
        ......55dddd....
        ......55dede....
        ....455ddddd....
        ....55..ddd.....
        ...45.efddd.....
        ...44.ee3333....
        .....333e33333..
        .....33d3eee33..
        ......333333ed..
        ......3333333e..
        ......3333333.e.
        ......6666666...
        ......66...66...
        ......66...66...
        ......66...66...
        ......66...66...
        ......dd...dd...
        .....999...999..
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
} else {
    girl = false
    mySprite2 = sprites.create(img`
        ........ff......
        ......ffffff....
        ......ffffff....
        .....fffffff....
        .....fffddfff...
        .....ffdededff..
        .....ffdfdfdff..
        ....fffdfdfdff..
        ....fffddddfffc.
        ....ffffddfffcf.
        ...ffffbbbbbcff.
        ..fffffbbbbcbff.
        ..ffffbbe1cbbff.
        ..fffffeee1bfff.
        ...fffffeeeffff.
        ...ffffe55effff.
        ....fff5555ffff.
        ....fff5555ffff.
        ....fff5555fff..
        .....ff5555fff..
        .......55f5.....
        .......5..5.....
        .......5..f.....
        .......5........
        .......5........
        .......f........
        `, SpriteKind.Player)
    controller.moveSprite(mySprite2)
    scene.cameraFollowSprite(mySprite2)
}
tiles.setTilemap(tilemap`level1`)
